### ISSUE TITLE
Maintain local index

### ISSUE THREAD

**Issue by Parth-Mehrotra** [tldr-pages/tldr-cpp-client#10]
I'm sure this feature is on the horizon, is this the right time to startup this discussion?

**Comment by Leandros** [comment]
Yes, it is on my to do list.
Should be pretty easy, write every request into some sort of local database
and get them from there with every new request.

On Thursday, 7 January 2016, Parth Mehrotra <notifications@github.com>
wrote:

> I'm sure this feature is on the horizon, is this the right time to startup
> this discussion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tldr-pages/tldr-cpp-client/issues/10>.
>


-- 
Mit freundlichen Grüßen, / Yours sincerely,

Arvid Gerstmann <ag@arvid-g.de>

---
Portfolio: http://arvid-gerstmann.de
Twitter: http://twitter.com/ArvidGerstmann
Google+: http://google.com/+ArvidGerstmann
---

**Comment by Leandros** [comment]
And it's done!
