### ISSUE TITLE
Client squashes dashes in command descriptions

### ISSUE THREAD

**Issue by notpeter** [tldr-pages/tldr-cpp-client#11]
For example from w.md
````markdown
- Show logged-in users info:
````
is rendered as "Show loggedin users info" (no dash)
![image](https://cloud.githubusercontent.com/assets/145113/12371805/063475ee-bbf5-11e5-98c6-922cd4c2d03c.png)

**Comment by notpeter** [comment]
Also globs are rendered inconsistently, even inside a code block
![image](https://cloud.githubusercontent.com/assets/145113/12374317/a8f063f4-bc4c-11e5-8ec0-f24a7192da66.png)

**Comment by Leandros** [comment]
How should they be rendered?

On Saturday, 16 January 2016, Peter Tripp <notifications@github.com> wrote:

> Also globs are rendered inconsistently, even inside a code block
> [image: image]
> <https://cloud.githubusercontent.com/assets/145113/12374317/a8f063f4-bc4c-11e5-8ec0-f24a7192da66.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tldr-pages/tldr-cpp-client/issues/11#issuecomment-172254790>
> .
>


-- 
Mit freundlichen Grüßen, / Yours sincerely,

Arvid Gerstmann <ag@arvid-g.de>

---
Portfolio: http://arvid-gerstmann.de
Twitter: http://twitter.com/ArvidGerstmann
Google+: http://google.com/+ArvidGerstmann
---

**Comment by Leandros** [comment]
Now renders the dashes as well, not sure what you mean with the globs, though, but I believe it's also fixed.
