### ISSUE TITLE
provide --platform option

### ISSUE THREAD

**Issue by luebken** [tldr-pages/tldr-cpp-client#13]
I know there are other clients to choose from but I just want to leave it here as an idea as this is the default clients.

sometimes I want to look up tldr for a different os or see the difference. in this case the bash version comes in handy:

https://github.com/raylee/tldr
```
USAGE: tldr [options] <command>

[options]
    -l, --list:      show all available pages
    -p, --platform:  show page from specific platform rather than autodetecting
    -u, --update:    update, force retrieving latest copies of locally cached files
    -h, -?, --help:  this help overview
````

**Comment by Leandros** [comment]
:+1:

**Comment by Leandros** [comment]
Has been added.
