### ISSUE TITLE
Find version without using git

### ISSUE THREAD

**Issue by danielcompton** [tldr-pages/tldr-cpp-client#19]
When Homebrew installs a package, it removes the .git folder to make sure all builds are reproducible. When I run make, an error is printed:

```
fatal: Not a git repository (or any of the parent directories): .git
```

from the `git describe` command in the Makefile. It would be great if there was also a way to build the project and get the version without needing git. I'm not quite sure what the best approach is here.

**Comment by Leandros** [comment]
I'll take care of that, and once it's done do a new release for #18

**Comment by Leandros** [comment]
I'm now both checking if the current directory is a git repository, and check if git itself exists. If either isn't met, I'll use the hardcoded version string.
