### ISSUE TITLE
Feature Request: show the Man page when there is no TLDR page

### ISSUE THREAD

**Issue by snoblenet** [tldr-pages/tldr-cpp-client#25]
At present, when there is no matching TLDR page, the client asks you submit one.

That's great, and should continue, but it might be an idea to also automatically show the Man page at that point.

**Comment by Paspartout** [comment]
You can write a simple script or shell function to do just that:
```bash
tldman() {
        tldr $1 || man $1
}
```

**Comment by snoblenet** [comment]
Thanks. I settled on:
```
help() {
  echo "$(tldr $1) \n $(man $1)" | less -R
}
```
If I come across any other similar tools (e.g. something that provides a link to the tool in question's repo, etc) then I'll add them to the function too.
