### ISSUE TITLE
Bash on Ubuntu on Windows - TLDR does not find pages

### ISSUE THREAD

**Issue by j86989** [tldr-pages/tldr-cpp-client#32]
## Reproduction Rate
I could reproduce the issue each time I tried to print any `TLDR` page.

## Steps to Reproduce
1. Install Windows Subsystem for Linux.
2. Install Ubuntu on Windows.
3. Run Bash on Ubuntu on Windows.
4. Install `linuxbrew`. There is installation instruction on `http://linuxbrew.sh`.
5. Install `TLDR` `C++` client: `brew update` and `brew install tldr`.
6. Try to print any `TLDR` page.

## Result
```bash
$ tldr tldr
This page doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr
```
```bash
$ tldr apt
This page doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr
```

## Expected Result
`TLDR` pages

## Additional Information
Windows Subsystem for Linux, Bash on Ubuntu on Windows
`TLDR` `C++` has been installed with [`linuxbrew`](http://linuxbrew.sh)

The issue might be related to issue #33 - `TLDR` local database cannot be updated.

**Comment by zdroid** [comment]
The issue should be either fixed in ae5dbdfbec98e1ce0a3c3c244904e2f3cd99510c or indentical to #33. I'll try to find out what causes the latter.
