### ISSUE TITLE
 C++ style comments are not allowed in ISO C90

### ISSUE THREAD

**Issue by yzcj105** [tldr-pages/tldr-cpp-client#50]
It seems that some gcc compiles does not accept "//" for comment, when `-ansi` flag is turned on in Makefile.  

make PREFIX=/mnt/home/jchen/.linuxbrew/Cellar/tldr/1.3.0_2 install
Last 15 lines from /mnt/home/jchen/.cache/Homebrew/Logs/tldr/01.make:
PREFIX=/mnt/home/jchen/.linuxbrew/Cellar/tldr/1.3.0_2
install

CC src/local.c
CC src/net.c
CC src/parser.c
CC src/tldr.c
CC src/utils.c
In file included from src/utils.c:12:0:
/mnt/home/jchen/.linuxbrew/Cellar/libzip/1.5.2_1/include/zip.h:261:1: error: C++ style comments are not allowed in ISO C90
 // clang-format on

**Comment by yzcj105** [comment]
One possible option to solve it is to remove "-ansi" flag in Makefile.

**Comment by zdroid** [comment]
Thank you for noting, fixed.
